### ISSUE TITLE
Items get deselected when list scrolls off-screen

### ISSUE THREAD

**Issue by zipgenius** [ManuelPeinado/MultiChoiceAdapter#5]
In order to reproduce the issue: add LOTS of items to the arrays in arrays.xml file of the sample application. Run the BaseAdapterDemo and select 3 or 4 items in list.
Then scroll down until selected items go off-screen: you will see the selected items count decrease until the ActionBar gose back to non-contextual mode and items are not selected anymore.

**Comment by ManuelPeinado** [comment]
Good catch, I'll look into it!

**Comment by ManuelPeinado** [comment]
Interesting, it only seems to happen when the list has checkboxes. Let's keep investigating

**Comment by ManuelPeinado** [comment]
Fixed on 2.1.2. Code already in the github repo, artifacts should be in maven central in a couple hours.

**Comment by fedefernandez** [comment]
I'm still having problems with this bug. I think you need to call setTag before setChecked in [MultiChoiceAdapterHelper.initItemCheckBox method](https://github.com/ManuelPeinado/MultiChoiceAdapter/blob/master/library/src/com/manuelpeinado/multichoiceadapter/MultiChoiceAdapterHelper.java#L298) because in recycled views setChecked will trigger onCheckedChanged method with an old tag value.

**Comment by ManuelPeinado** [comment]
@projectsexception I've switched the calls to setTag and setChecked as you suggest (v2.2.4)
